version: 0.0
os: linux
files:
- source: /
  destination: /home/ubuntu/pipelinetest
hooks:  
AfterInstall:
  - location: scripts/installpkgs.sh
    timeout: 300
    runas: root
ApplicationStart:
 # - location: scripts/appstart.sh
  #  timeout: 300
   # runas: root
  location: scripts/pm2-start.sh
      timeout: 300
      runas: ubuntu    